// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnsvztqgtukktjrizrpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuc3Z6dHFndHVra3Rqcml6cnBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTI0OTAsImV4cCI6MjA2NjI2ODQ5MH0.VMmbk0hSENA6fl8d1m5NlV2moDTr8bDe_XPQhj0-dAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);